[package]
name = "toolbox"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
description = ""
categories = [ ]
keywords = [ ]
repository = ""
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".github",
  ".gitignore",
  "justfile",
  "manual.typ"
]