name: Build

on:
  push:
    tags: 
      - "*"
  workflow_dispatch:
    branches: [ main, dev ]

jobs:
  building:
    name: Build package and example locally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup just
        uses: extractions/setup-just@v3
      - name: Setup typst
        uses: typst-community/setup-typst@v4
      - name: Running build script
        run: just build
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typst-build-results
          path: dev/example/*
          retention-days: 5