name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tests:
    name: Test for ${{ matrix.typst-version.typst }} (Tytanic ${{ matrix.typst-version.tytanic }}${{ matrix.typst-version.doc && ', with docs' }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup just
        uses: extractions/setup-just@v3
      - name: Setup typst
        uses: typst-community/setup-typst@v4
      - name: Setup tytanic
        uses: typst-community/setup-tytanic@v1
      - name: Run test suite
        run: just test
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typst-${{ steps.setup-typst.outputs.typst-version }}-test-results
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5